apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-app-config
  namespace: app-dev
  labels:
    app.kubernetes.io/part-of: demo-app
    environment: dev
    owner: platform-team
data:
  ENV_NAME: dev
  LOG_LEVEL: debug