# ServiceAccount représentant le développeur
# En vrai projet : ce serait un utilisateur OIDC/cert, ici on simule avec un SA
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-user
  namespace: app-dev
  labels:
    app.kubernetes.io/part-of: demo-app
    environment: dev
    owner: platform-team
